version: 2.1

jobs:
    run-build:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              sudo chmod +x /bin/hadolint

        - run:
            name: Run Lint
            command: |
              hadolint Dockerfile

        - setup_remote_docker:
            version: 19.03.13

        - run:
            name: Build Docker Image
            command: |
              docker build -t kelanik8/capstone_project .

        - run:
            name: Push Docker Image to Docker Hub
            command: |
              docker build -t kelanik8/capstone_project .
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
              docker push kelanik8/capstone_project
          
        - run:
            name: Install packages
            command: |
              apk add curl tar gzip
              apk add --update sudo
              pip install awscli
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
              kubectl version --client
              curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
              sudo mv /tmp/eksctl /usr/local/bin

workflows:
  default:
    jobs:
      - run-build