version: 2.1

jobs:
    run-lint:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              sudo chmod +x /bin/hadolint
        - run:
            name: Run Lint
            command: |
              hadolint Dockerfile

    build-docker-image:
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - checkout
        - run:
            name: Build Docker Image
            command: |
              docker build -t kelanik8/capstone_project .

    push-docker-image:
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - checkout
        - run:
            name: Push Docker Image to Docker Hub
            command: |
              docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD 
              docker push kelanik8/capstone_project


workflows:
  default:
    jobs:
      - run-lint
      - build-docker-image
      - push-docker-image